cc_binary(
  name = "singleton",
  srcs = ["main.cc"],
  # copts = [],
  deps = ["single"],
)

cc_library(
  name = "single",
  # srcs = ["single.h"],
  hdrs = ["single.h"],
  # deps = ["header files"],
)